// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLEjQaPGBKhhVE6IWq7PiEDDfZ20SjAY',
    appId: '1:619002836060:android:2d52fb7bcba62500596299',
    messagingSenderId: '619002836060',
    projectId: 'aquamans-47d16',
    databaseURL: 'https://aquamans-47d16-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquamans-47d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJ571OeKAibV-VpSZ61k2RMFkMNiv-TI',
    appId: '1:619002836060:ios:042eb68074872a49596299',
    messagingSenderId: '619002836060',
    projectId: 'aquamans-47d16',
    databaseURL: 'https://aquamans-47d16-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquamans-47d16.firebasestorage.app',
    iosBundleId: 'com.example.aquacareV5',
  );

}