// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhL7beuFqY4NMaT4saNDninLM9kbBZwMk',
    appId: '1:48514923286:android:cdd129564b9a9851232e37',
    messagingSenderId: '48514923286',
    projectId: 'aquacare-310103',
    databaseURL:
        'https://aquacare-310103-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'aquacare-310103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvKLQ2Y6jFIiFEGh0TAkI94nUskvk3Yo',
    appId: '1:48514923286:ios:0b3f820846c7426a232e37',
    messagingSenderId: '48514923286',
    projectId: 'aquacare-310103',
    databaseURL:
        'https://aquacare-310103-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'aquacare-310103.firebasestorage.app',
    iosBundleId: 'com.example.aquacareV5',
  );
}
