// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKWNQRZakZk0begIFTLWjuBXbfP2jVHCg',
    appId: '1:1009954792101:android:ba9fd9e3ca153795f1a34c',
    messagingSenderId: '1009954792101',
    projectId: 'for-practice-ce750',
    databaseURL: 'https://for-practice-ce750-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'for-practice-ce750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9cUBM3BsjZb1Cw8FdvcXbcEnpQEz5aaY',
    appId: '1:1009954792101:ios:1fd6c2c07686fe00f1a34c',
    messagingSenderId: '1009954792101',
    projectId: 'for-practice-ce750',
    databaseURL: 'https://for-practice-ce750-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'for-practice-ce750.firebasestorage.app',
    iosBundleId: 'com.example.aquacareV5',
  );

}